# Generated by Django 5.0.2 on 2025-07-07 23:12

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_product_description_alter_vendor_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The official name of your brand that will appear in the logo', max_length=100, verbose_name='Brand Name')),
                ('title', models.CharField(help_text='The main marketing message or slogan for your brand', max_length=100, verbose_name='Brand Tagline')),
                ('description', models.TextField(help_text='A short description of your brand and what it represents', max_length=255, verbose_name='Brand Description')),
                ('advertisement', models.CharField(blank=True, help_text='Special offer or promotion header text (e.g., "Summer Sale - 30% Off")', max_length=100, null=True, verbose_name='Promotional Header')),
                ('logo', models.ImageField(blank=True, help_text='Upload the main brand logo (Recommended: transparent PNG, max 500x200px)', null=True, upload_to=core.models.brand_logo_upload_path, verbose_name='Logo')),
                ('favicon', models.ImageField(blank=True, help_text='Small icon that appears in browser tabs (recommended size: 32x32px)', null=True, upload_to='brand/favicon/', verbose_name='Favicon')),
            ],
            options={
                'verbose_name': 'Brand Info',
                'verbose_name_plural': 'Brand Info',
            },
        ),
    ]
