# Generated by Django 5.0.2 on 2025-07-09 14:48

import ckeditor_uploader.fields
import core.models
import django.core.validators
import django.db.models.deletion
import shortuuid.django_fields
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_brandinfo'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='cartitem',
            name='core_cartit_order_i_de902f_idx',
        ),
        migrations.RemoveIndex(
            model_name='cartitem',
            name='core_cartit_user_id_c79c77_idx',
        ),
        migrations.RemoveIndex(
            model_name='cartitem',
            name='core_cartit_product_70953e_idx',
        ),
        migrations.RemoveIndex(
            model_name='cartitem',
            name='core_cartit_item_st_54cfe8_idx',
        ),
        migrations.RemoveIndex(
            model_name='cartorder',
            name='core_cartor_order_i_18ba3c_idx',
        ),
        migrations.RemoveIndex(
            model_name='cartorder',
            name='core_cartor_user_id_9c770c_idx',
        ),
        migrations.RemoveIndex(
            model_name='cartorder',
            name='core_cartor_status_2c1d65_idx',
        ),
        migrations.RemoveIndex(
            model_name='cartorder',
            name='core_cartor_paid_st_335d95_idx',
        ),
        migrations.RemoveIndex(
            model_name='cartorder',
            name='core_cartor_created_3ea50e_idx',
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='core_catego_title_4dd14c_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='core_produc_title_05e747_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='core_produc_slug_42f8f6_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='core_produc_price_c510fe_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='core_produc_is_acti_1d1aa8_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='core_produc_categor_784c92_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='core_produc_vendor__852b67_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='core_produc_status_b17a10_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='core_produc_is_feat_ba4bd5_idx',
        ),
        migrations.RemoveIndex(
            model_name='productimage',
            name='core_produc_product_b0d6d1_idx',
        ),
        migrations.RemoveIndex(
            model_name='productimage',
            name='core_produc_date_15dfae_idx',
        ),
        migrations.RemoveIndex(
            model_name='productreview',
            name='core_produc_product_36c312_idx',
        ),
        migrations.RemoveIndex(
            model_name='productreview',
            name='core_produc_user_id_597986_idx',
        ),
        migrations.RemoveIndex(
            model_name='productreview',
            name='core_produc_rating_eb0280_idx',
        ),
        migrations.RemoveIndex(
            model_name='productreview',
            name='core_produc_date_ad_79a150_idx',
        ),
        migrations.RemoveIndex(
            model_name='vendor',
            name='core_vendor_name_91f195_idx',
        ),
        migrations.RemoveIndex(
            model_name='vendor',
            name='core_vendor_rating_e9ac4a_idx',
        ),
        migrations.RemoveIndex(
            model_name='vendor',
            name='core_vendor_is_veri_0e494c_idx',
        ),
        migrations.RemoveIndex(
            model_name='wishlist',
            name='core_wishli_user_id_b5812e_idx',
        ),
        migrations.RemoveIndex(
            model_name='wishlist',
            name='core_wishli_product_f972a2_idx',
        ),
        migrations.RemoveIndex(
            model_name='wishlist',
            name='core_wishli_date_ad_83fa51_idx',
        ),
        migrations.AlterField(
            model_name='brandinfo',
            name='advertisement',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Promotional Header'),
        ),
        migrations.AlterField(
            model_name='brandinfo',
            name='description',
            field=models.TextField(max_length=255, verbose_name='Brand Description'),
        ),
        migrations.AlterField(
            model_name='brandinfo',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='brand/favicon/', verbose_name='Favicon'),
        ),
        migrations.AlterField(
            model_name='brandinfo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.brand_logo_upload_path, verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='brandinfo',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Brand Name'),
        ),
        migrations.AlterField(
            model_name='brandinfo',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Brand Tagline'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='item_status',
            field=models.CharField(choices=[('drafted', 'Drafted'), ('pending', 'Pending'), ('processing', 'Processing'), ('awaiting_payment', 'Awaiting Payment'), ('awaiting_dispatch', 'Awaiting Dispatch'), ('shipping', 'Shipping'), ('delivered', 'Delivered'), ('published', 'Published'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('returned', 'Returned'), ('refunded', 'Refunded'), ('failed', 'Failed'), ('rejected', 'Rejected'), ('on_hold', 'On Hold'), ('disputed', 'Disputed'), ('under_review', 'Under Review'), ('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='pending', max_length=20, verbose_name='Item Status'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.cartorder', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit Price'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='core.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Invoice Number'),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='order_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=10, max_length=20, prefix='ord_', unique=True, verbose_name='Order ID'),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='paid_status',
            field=models.BooleanField(default=False, verbose_name='Payment Status'),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Payment Date'),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='shipping_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Shipping Cost'),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='status',
            field=models.CharField(choices=[('drafted', 'Drafted'), ('pending', 'Pending'), ('processing', 'Processing'), ('awaiting_payment', 'Awaiting Payment'), ('awaiting_dispatch', 'Awaiting Dispatch'), ('shipping', 'Shipping'), ('delivered', 'Delivered'), ('published', 'Published'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('returned', 'Returned'), ('refunded', 'Refunded'), ('failed', 'Failed'), ('rejected', 'Rejected'), ('on_hold', 'On Hold'), ('disputed', 'Disputed'), ('under_review', 'Under Review'), ('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='pending', max_length=20, verbose_name='Order Status'),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Tax Amount'),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Order Total'),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/', validators=[core.models.validate_image_size], verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_products', to='core.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='digital',
            field=models.BooleanField(default=False, verbose_name='Digital Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.user_directory_path, validators=[core.models.validate_image_size], verbose_name='Main Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Archived'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_best_seller',
            field=models.BooleanField(default=False, verbose_name='Best Seller'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_discounted',
            field=models.BooleanField(default=False, verbose_name='Discounted'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Featured'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=True, verbose_name='New Arrival'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_on_sale',
            field=models.BooleanField(default=False, verbose_name='On Sale'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Published'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_refundable',
            field=models.BooleanField(default=True, verbose_name='Refundable'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_returnable',
            field=models.BooleanField(default=True, verbose_name='Returnable'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Verified'),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Original Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, length=10, max_length=20, prefix='prod_', unique=True, verbose_name='Product ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Current Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=10, max_length=20, prefix='sku_', unique=True, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=models.TextField(blank=True, null=True, verbose_name='Specifications'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('drafted', 'Drafted'), ('pending', 'Pending'), ('processing', 'Processing'), ('awaiting_payment', 'Awaiting Payment'), ('awaiting_dispatch', 'Awaiting Dispatch'), ('shipping', 'Shipping'), ('delivered', 'Delivered'), ('published', 'Published'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('returned', 'Returned'), ('refunded', 'Refunded'), ('failed', 'Failed'), ('rejected', 'Rejected'), ('on_hold', 'On Hold'), ('disputed', 'Disputed'), ('under_review', 'Under Review'), ('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='drafted', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock Quantity'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='product',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.vendor', verbose_name='Vendor'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Added'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=core.models.user_directory_path, validators=[core.models.validate_image_size], verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='core.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Added'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, '⭐★★★★'), (2, '⭐⭐★★★'), (3, '⭐⭐⭐★★'), (4, '⭐⭐⭐⭐★'), (5, '⭐⭐⭐⭐⭐')], default=5, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='review',
            field=models.TextField(blank=True, null=True, verbose_name='Review'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Is Verified'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Added'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to='core.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
