# Generated by Django 5.0.2 on 2025-07-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_coupon_sitesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='items_sold',
            field=models.PositiveIntegerField(default=0, verbose_name='Items Sold'),
        ),
    ]
