# Generated by Django 5.0.2 on 2025-07-14 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_product_items_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number'),
        ),
    ]
