# Generated by Django 5.0.2 on 2025-07-15 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_productcolor_productsize'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='color_hex',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Color Hex'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='color_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Color Name'),
        ),
    ]
